name: SonarCloud Analysis

on:
  push:
    branches:
      - release
  pull_request:

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Install SonarScanner
      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner.zip -d $HOME
          echo "$HOME/sonar-scanner-4.8.0.2856-linux/bin" >> $GITHUB_PATH
          export PATH="$HOME/sonar-scanner-4.8.0.2856-linux/bin:$PATH"
          echo "SonarScanner installed and PATH updated"

      # Step 5: Setup Java (Optional, but recommended if not already set up)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Step 6: Run SonarCloud Scan
      - name: Run SonarCloud Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=MatanLank_harmony-endpoint-management-py-sdk \
            -Dsonar.organization=MatanLank \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.DEVSEC01 }}

