name: SonarCloud Analysis

on:
  push:
    branches:
      - release
  pull_request:

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Install SonarScanner
      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner.zip -d $HOME
          echo "$HOME/sonar-scanner-4.8.0.2856-linux/bin" >> $GITHUB_PATH

      # Step 5: Verify Java Installation
      - name: Verify Java Installation
        run: java -version

      # Step 6: Debug SonarScanner Installation
      - name: Debug SonarScanner Installation
        run: |
          echo "PATH: $PATH"
          ls -l $HOME/sonar-scanner-4.8.0.2856-linux/bin
          sonar-scanner --version || echo "SonarScanner not found or not executable"

      # Step 7: Run SonarCloud Scan
      - name: Run SonarCloud Scan
        env:
          PATH: ${{ env.PATH }}:$HOME/sonar-scanner-4.8.0.2856-linux/bin
        run: |
          sonar-scanner \
          -Dsonar.projectKey=MatanLank_harmony-endpoint-management-py-sdk \
          -Dsonar.organization=MatanLank \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.DEVSEC01 }}

