name: SonarCloud Analysis

on:
  push:
    branches:
      - release
  pull_request:

jobs:
  sonaranalysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Step 3: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 5: Install SonarScanner
      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner.zip -d $HOME
          export PATH=$HOME/sonar-scanner-4.8.0.2856-linux/bin:$PATH
          echo "export PATH=$HOME/sonar-scanner-4.8.0.2856-linux/bin:$PATH" >> $HOME/.bashrc
          echo "SonarScanner installed and PATH updated"

      # Step 6: Debug PATH and SonarScanner Installation
      - name: Debug PATH and SonarScanner
        run: |
          export PATH=$HOME/sonar-scanner-4.8.0.2856-linux/bin:$PATH
          echo "PATH: $PATH"
          ls -l $HOME/sonar-scanner-4.8.0.2856-linux/bin
          echo "Checking sonar-scanner version:"
          $HOME/sonar-scanner-4.8.0.2856-linux/bin/sonar-scanner --version || echo "SonarScanner not found or not executable"

      # Step 7: Run SonarCloud Scan
      - name: Run SonarCloud Scan
        run: |
          export PATH=$HOME/sonar-scanner-4.8.0.2856-linux/bin:$PATH
          $HOME/sonar-scanner-4.8.0.2856-linux/bin/sonar-scanner \
          -Dsonar.projectKey=MatanLank_harmony-endpoint-management-py-sdk \
          -Dsonar.organization=MatanLank \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.DEVSEC01 }}

