name: SonarCloud Analysis

on:
  push:
    branches:
      - release
  pull_request:

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner.zip
          export PATH="$PWD/sonar-scanner-4.8.0.2856-linux/bin:$PATH"
          echo "SonarScanner installed and path updated"

      - name: Run SonarCloud Scan
        run: |
          sonar-scanner \
          -Dsonar.projectKey=MatanLank_harmony-endpoint-management-py-sdk \
          -Dsonar.organization=MatanLank \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.DEVSEC01 }}



