name: SonarCloud Analysis

on:
  push:
    branches:
      - release
  pull_request:

jobs:
  sonarqube:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java (Java 17 is required by SonarScanner)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 5: Run SonarScanner CLI via Docker
      - name: SonarCloud Scan with Docker
        env:
          SONAR_TOKEN: ${{ secrets.DEVSEC01 }} # Your SonarCloud token stored as a GitHub secret
        run: |
          docker run --rm \
          -e SONAR_TOKEN="${SONAR_TOKEN}" \
          -v "${{ github.workspace }}:/usr/src" \
          sonarsource/sonar-scanner-cli:latest \
          sonar-scanner \
          -Dsonar.projectKey=MatanLank_harmony-endpoint-management-py-sdk \
          -Dsonar.organization=matanlank80 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.sources=.

