name: CI Workflow

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  sonarqube:
    name: SonarCloud Analysis and JFrog XRay Scan
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 5: SonarCloud Scan with Docker
      - name: SonarCloud Scan with Docker
        env:
          SONAR_TOKEN: ${{ secrets.DEVSEC01 }} # Your SonarCloud token stored as a GitHub secret
        run: |
          docker run --rm \
          -e SONAR_TOKEN="${SONAR_TOKEN}" \
          -v "${GITHUB_WORKSPACE}:/usr/src" \
          sonarsource/sonar-scanner-cli:latest \
          sonar-scanner \
          -Dsonar.projectKey=MatanLank_harmony-endpoint-management-py-sdk \
          -Dsonar.organization=matanlank80 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.sources=.

      # Step 6: Create Artifact
      - name: Create Artifact
        run: zip -r artifact.zip folder1/package1

      # Step 7: Upload Artifact to JFrog Artifactory
      - name: Upload Artifact to JFrog Artifactory
        env:
          JFROG_IDENTITY_TOKEN: ${{ secrets.JFROG_IDENTITY_TOKEN }}
        run: |
          curl -u "admin:${JFROG_IDENTITY_TOKEN}" \
          -T artifact.zip \
          "https://matanlank.jfrog.io/artifactory/matan-pypi-repo-pypi/folder1/package1.zip"

      # Step 8: Trigger JFrog XRay Scan
      - name: Trigger JFrog XRay Scan
        env:
          JFROG_IDENTITY_TOKEN: ${{ secrets.JFROG_IDENTITY_TOKEN }}
        run: |
          curl -X POST "https://matanlank.jfrog.io/xray/api/v1/scanArtifact" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${JFROG_IDENTITY_TOKEN}" \
          -d '{
            "repo_key": "matan-pypi-repo-pypi",
            "artifact_path": "folder1/package1.zip"
          }'

      # Step 9: Check SonarCloud Quality Gate
      - name: Check SonarCloud Quality Gate
        env:
          SONAR_TOKEN: ${{ secrets.DEVSEC01 }}
        run: |
          status=$(curl -s -u "${SONAR_TOKEN}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=MatanLank_harmony-endpoint-management-py-sdk" | jq -r '.projectStatus.status')
          if [ "$status" != "OK" ]; then
            echo "Quality Gate failed: $status"
            exit 1
          fi

      # Step 10: Check JFrog XRay Scan Results
      - name: Check JFrog XRay Scan Results
        env:
          JFROG_IDENTITY_TOKEN: ${{ secrets.JFROG_IDENTITY_TOKEN }}
        run: |
          scan_result=$(curl -s -X GET "https://matanlank.jfrog.io/xray/api/v1/scanArtifact" \
          -H "Authorization: Bearer ${JFROG_IDENTITY_TOKEN}")
          critical_issues=$(echo "$scan_result" | jq -r '.data.issues[] | select(.severity == "Critical")')
          if [ -n "$critical_issues" ]; then
            echo "Critical issues found in JFrog XRay scan."
            exit 1
          fi

