on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  sonarqube:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      # Existing steps (SonarCloud, etc.)
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: SonarCloud Scan with Docker
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Your SonarCloud token stored as a GitHub secret
        run: |
          docker run --rm \
          -e SONAR_TOKEN="${SONAR_TOKEN}" \
          -v "${GITHUB_WORKSPACE}:/usr/src" \
          sonarsource/sonar-scanner-cli:latest \
          sonar-scanner \
          -Dsonar.projectKey=MatanLank_harmony-endpoint-management-py-sdk \
          -Dsonar.organization=matanlank80 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.sources=.

      # New Step: Upload Artifact to JFrog Artifactory
      - name: Upload Artifact to JFrog Artifactory
        env:
          JFROG_IDENTITY_TOKEN: ${{ secrets.JFROG_IDENTITY_TOKEN }}
        run: |
          curl -u "admin:${JFROG_IDENTITY_TOKEN}" \
          -T <your_artifact_file> \
          "https://<your_artifactory_url>/artifactory/<repo_name>/<artifact_path>"

      # New Step: Trigger JFrog XRay Scan
      - name: Trigger JFrog XRay Scan
        env:
          JFROG_IDENTITY_TOKEN: ${{ secrets.JFROG_IDENTITY_TOKEN }}
        run: |
          curl -X POST "https://<your_artifactory_url>/xray/api/v1/scanArtifact" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${JFROG_IDENTITY_TOKEN}" \
          -d '{
            "repo_key": "<repo_name>",
            "artifact_path": "<artifact_path>"
          }'

